### ISSUE TITLE
Multiple input blow5 files (blow5 dir as input)

### ISSUE THREAD

**Issue by hiruna72** [Psy-Fer/buttery-eel#11]
Hey, can multiproc branch have a blow5 directory as the input?

**Comment by Psy-Fer** [comment]
Yea sure.

I'll make the input check do see if it's a file or dir and then do recursive processing.

**Comment by Psy-Fer** [comment]
I have implemented this in v0.3.0 of the multiproc branch. We will be merging that into main soon.
