### ISSUE TITLE
Add some read-id list for selective basecalling

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/buttery-eel#15]
Allow a user to provide a list of read-ids to basecall.

This will then use random access get calls to pyslow5

**Comment by hasindu2008** [comment]
I think this is not that necessary, the user can simply use slow5tools get to generate a BLOW5 file and then call the buttery-eel on that new file.

**Comment by Psy-Fer** [comment]
indeed, but it means they don't have to generate a new file at all.
