### ISSUE TITLE
Gets many reads skipped with dorado

### ISSUE THREAD

**Issue by uaudith** [Psy-Fer/buttery-eel#21]
Here are the versions I used

```
dorado_basecall_server --version
Dorado Basecall Service Software, (C)Oxford Nanopore Technologies plc. Version 7.1.4+d7df870c0, client-server API version 15.0.0

buttery-eel --version
buttery-eel - wrapping guppy for SLOW5 basecalling version: 0.3.3
```

When methylation calling using the following command,
`buttery-eel -g ont-dorado-server/bin --config dna_r10.4.1_e8.2_400bps_modbases_5mc_cg_sup_prom.cfg -i PGXX22394_reads_chr22.blow5 -o out.sam --call_mods --port 5557`

I get the following message for around 50 different read IDs
`Skipped a read: {read-id}`

This did not happen with guppy+buttery-eel. I appreciate it if you could take a look.
Thank you

**Comment by Psy-Fer** [comment]
Hey there,

could you please update to version 0.4.1 and try again? This is the latest version (I released it yesterday), for supporting dorado-server.

Also it looks like you aren't providing a device argument to say which GPU you are calling with. It could be then defaulting to CPU mode and timing out. I would advise always providing a device argument, even it it's just `--device 'cuda:all'`

Let me know how you go.
James
