### ISSUE TITLE
Can Guppy ont-pyguppy-client-lib version compatible with Doradoont-pyguppy-client-lib  version？

### ISSUE THREAD

**Issue by kir1to455** [Psy-Fer/buttery-eel#29]
Hi,
I have already downloaded the guppy version 6.3.8 and ont-pyguppy-client-lib==6.3.8 before.
Now I need to use Dorado new RNA model: rna004_130bps_sup@v3.0.1, do I need to reinstall ont pyguppy client lib? (Or do I need to create a new virtual environment like "venv3"?
My Dorado basecall server is v7.2.13.

Best wishes,
Kirito

**Comment by Psy-Fer** [comment]
Hello Kirito,

You can either make a new virtual env, and install everything again there with the new ont-pyguppy-client-lib updated to match the version you need, and then you can simply switch between versions using `source ./venv-${VERSION}/bin/activate`. Or you can update the version in the 1 venv you have already made and just use that.

I hope that helps.

James
