### ISSUE TITLE
move_and_trace_enabled has changed to move_enabled in ont-pybasecall-client-lib 7.4.12

### ISSUE THREAD

**Issue by michaelodear** [Psy-Fer/buttery-eel#40]
Hi James,

Just wanted to flag for your attention that the name of this parameter has changed in the latest version of the ont-dorado server, for no specific reason it seems, preventing users from calling base modifications with this version of the server. I ran into it when trying to call 6mA modifications on my own data just this week. Fortunately it's a simple fix of basecall.py so not the most frustrating error in the world.

Cheers,
Michael

**Comment by Psy-Fer** [comment]
Hey, 

Thanks so much for flagging this.
I'll push through a patch.

This stuff happens all the time with ONT, so I'm not even a little bit surprised.

I'll leave this ticket open until I push the new version.

Cheers 
James

**Comment by Psy-Fer** [comment]
Hello,

This should now be resolved in https://github.com/Psy-Fer/buttery-eel/releases/tag/v0.5.0

Cheers
James
