### ISSUE TITLE
 Connection error. [timed_out] Failed to establish connection with address

### ISSUE THREAD

**Issue by edeuse** [Psy-Fer/buttery-eel#46]
[**I continue to encounter the error**

**[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002.** 

**Despite verifying that there are no firewall settings blocking the connection, the issue persists.** 

**I also tried using '--port auto --use_tcp' and specifying a specific port with '--port (number) --use_tcp', but the same errors occurred. Below are the scripts**]
``
./eel -g /home/edeus/ont-dorado-server/bin --config dna_r10.4.1_e8.2_400bps_5khz_sup.cfg --device cuda:all -i /mnt/e/PWS/240430/G2213161/analysis/G2213161.blow5 -o /mnt/e/PWS/240430/G2213161/analysis/buttery-eel/G2213161.blow5to.fastq

![image](https://github.com/user-attachments/assets/071ac7c2-fe48-466a-9806-fecf1c3dfa70)

trying port 5000
trying port 5001
trying port 5002
Using port 5002

               ~  buttery-eel - SLOW5 Guppy/Dorado Server Basecalling  ~
                            version: 0.4.3
==========================================================================
  ARGS
==========================================================================
args:
 Namespace(input='/mnt/e/PWS/240430/G2213161/analysis/G2213161.blow5', output='/mnt/e/PWS/240430/G2213161/analysis/buttery-eel/G2213161.blow5to.fastq', guppy_bin=PosixPath('/home/edeus/ont-dorado-server/bin'), config='dna_r10.4.1_e8.2_400bps_5khz_sup.cfg', guppy_batchsize=4000, call_mods=False, qscore=None, slow5_threads=4, procs=4, slow5_batchsize=4000, quiet=False, max_read_queue_size=20000, log='buttery_basecaller_logs', moves_out=False, do_read_splitting=False, min_score_read_splitting=50.0, detect_adapter=False, min_score_adapter=60.0, trim_adapters=False, detect_mid_strand_adapter=False, seq_sum=False, barcode_kits=None, enable_trim_barcodes=False, require_barcodes_both_ends=False, detect_mid_strand_barcodes=False, min_score_barcode_front=60.0, min_score_barcode_rear=60.0, min_score_barcode_mid=60.0, duplex=False, single=False, profile=False, above_7310=True)
['--device', 'cuda:all', '--port', '5002', '--use_tcp']

==========================================================================
  Starting Guppy/Dorado Basecalling Server
==========================================================================
Setting params...
Connecting...
[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002
[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002
[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002
[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002
[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002
[ont/error] basecall_client::Client::worker_loop: Connection error. [timed_out] Failed to establish connection with address: tcp://localhost:5002
Traceback (most recent call last):
  File "/home/edeus/buttery-eel/venv3/bin/buttery-eel", line 33, in <module>
    sys.exit(load_entry_point('buttery-eel==0.4.3', 'console_scripts', 'buttery-eel')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edeus/buttery-eel/venv3/lib/python3.11/site-packages/buttery_eel-0.4.3-py3.11.egg/src/buttery_eel.py", line 145, in main
  File "/home/edeus/anaconda3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/edeus/buttery-eel/venv3/lib/python3.11/site-packages/buttery_eel-0.4.3-py3.11.egg/src/basecaller.py", line 97, in start_guppy_server_and_client
  File "/home/edeus/buttery-eel/venv3/lib/python3.11/site-packages/ont_pybasecall_client_lib-7.3.10-py3.11-linux-x86_64.egg/pybasecall_client_lib/pyclient.py", line 392, in __enter__
    self.connect()
  File "/home/edeus/buttery-eel/venv3/lib/python3.11/site-packages/ont_pybasecall_client_lib-7.3.10-py3.11-linux-x86_64.egg/pybasecall_client_lib/pyclient.py", line 186, in connect
    raise exception_type(exception_message)
ConnectionError: Query timed out: <result.timed_out: `4>`

**[The dorado_basecall_server appears to be functioning correctly, as indicated by the following output:]**

ONT Dorado basecall server software version 7.4.12+0e5e75c49, client-server API version 20.0.0, minimap2 version 2.27-r1193
log path:            /home/edeus/log
max queued reads:    33000
num socket threads:  2
max returned events: 256000
gpu device:          cpu
Use of this software is permitted solely under the terms of the end user license agreement (EULA).
By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.
The EULA may be found in /home/edeus/ont-dorado-server/bin

Config loaded:
config file:               /home/edeus/ont-dorado-server/data/dna_r10.4.1_e8.2_400bps_5khz_sup.cfg
model file:                /home/edeus/ont-dorado-server/data/dna_r10.4.1_e8.2_400bps_sup@v4.3.0
Starting server on port: ipc:///tmp/3d37-2a29-fb78-2c13

**[Given that the Dorado basecall server seems to be running without issue, I would appreciate any insights into why the buttery-eel fails to establish a connection, and what steps I might take to resolve this persistent issue.]**

**Comment by Psy-Fer** [comment]
Hey, 

Could you try with Dorado server and library 7.3.10 instead of 7.4.12?

7.4.12 changed a lot of the API, and I currently have a branch for that version (with backward compatibility) that is going to be the release for buttery-eel v0.5.0. only problem is I've been held up by a bug in the library that I've been waiting for feedback from ONT for a week now.

If you urgently need Dorado server 7.4.12, give that branch a try. It's mostly complete. Just a few bits and bobs with logging methylation models and redoing the Sam writing code. Fastq should work fine. Only warning is I haven't run it through or automated testing yet, so can't promise there aren't bugs.

Otherwise give me a few days next week and I should have an update our regardless of ONT get back to me or not. (Our lab also needs this update )

Let me know if you have any other feedback, and I'm sorry for the inconvenience


Cheers,
James

**Comment by Psy-Fer** [comment]
Oh, and the library is 7.3.10 and the Dorado server is 7.3.9 (ont did a patch before release of the python library so they don't match, but they are the 2 versions to be correctly paired.)

**Comment by Psy-Fer** [comment]
Hey
I just realised in your error messages

```
"/home/edeus/buttery-eel/venv3/lib/python3.11/site-packages/ont_pybasecall_client_lib-7.3.10-py3.11-linux-x86_64.egg/pybasecall_client_lib/pyclient.py", line 186, in connect
```
and
```
ONT Dorado basecall server software version 7.4.12+0e5e75c49, client-server API version 20.0.0, minimap2 version 2.27-r1193
```

This means you are using the dorado-server 7.4.12 and the ont_pybasecall_client_lib 7.3.10

You either need to downgrade dorado-server, or upgrade your pybasecall client lib to fix this issue.

James

**Comment by edeuse** [comment]
Thank you for your valuable advice; I will make sure to follow your suggestions. Thanks!

**Comment by edeuse** [comment]
Following your advice, all the errors were resolved after downgrading the dorado-server. Thank you!
