### ISSUE TITLE
Advice needed: Low percentage of CPU/GPU usage when basecalling

### ISSUE THREAD

**Issue by youyupei** [Psy-Fer/buttery-eel#5]
Hi @Psy-Fer  and @hasindu2008 ,

Hope you are doing well. I am trying to run a simulation analysis use squigglator and buttery-eel. The simulated BLOW5 file looks good. I am basecalling them using buttery-eel, but it seems the process does not use CPUs and GPUs super efficiently.
![image](https://user-images.githubusercontent.com/38273260/205004700-5ae9a2b4-d657-4467-b522-c7d576d0f84f.png)

 I am not sure whether I did anything wrong but here is the command I used for the run:
```
buttery-eel -i out_signal.blow5 -o sim.fastq -g ont-guppy/bin \
--config dna_r9.4.1_450bps_sup_Q7.cfg
-q 10 \
--port 5558 \
--use_tcp \
--device 'cuda:0 cuda:1'   \
--num_callers 1 \
--gpu_runners_per_device 8 \
--chunks_per_runner 1000  \
--cpu_threads_per_caller 16
```
I have tried multiple other settings but got similar patterns of CPU and GPU usage; I am not sure this is because I have a single large blow5 file as input. May I have some advice from you about this?

**Comment by Psy-Fer** [comment]
G'Day Yupei  You,

Yea the main branch of buttery eel is still the "original" version I released that is stable, but not efficient.

I have  a branch called `multiproc` https://github.com/Psy-Fer/buttery-eel/tree/multiproc 

You could give that a try, and run with the following command. It might be a bit faster for you......


```
buttery-eel -i out_signal.blow5 -o sim.fastq -g ont-guppy/bin \
--config dna_r9.4.1_450bps_sup_Q7.cfg
-q 10 \
--port 5558 \
--use_tcp \
--device 'cuda:0 cuda:1'   \
--chunks_per_runner 1000  \
--slow5_threads 20 \
--procs 10
---

**Comment by hasindu2008** [comment]
@youyupei @Psy-Fer 

What is the GPU on the server? Is it perhaps A100?

If it is Tesla V100, for a sup model, the single process version in the main branch should be adequate. 
On our server, the command `buttery-eel  -i a.blow5  -g /install/ont-guppy-6.3.7/bin/  --config dna_r9.4.1_450bps_sup.cfg --device 'cuda:0 cuda:1' -q 10 -o  a.fastq --port 5555  --use_tcp` brings the GPU usage to 97%
<img width="507" alt="image" src="https://user-images.githubusercontent.com/12987163/205024946-4eb3ac0c-888a-4a7f-ab2e-bcca053c7233.png">

By the way, is this `dna_r9.4.1_450bps_sup_Q7.cfg` a configuration file that you manually created?

**Comment by Psy-Fer** [comment]
Yea I should also mention that the process and thread control of guppy is mostly going to be ignored, so those flags aren't going to have much if any impact.

**Comment by Psy-Fer** [comment]
Oh and there was a small bug with `-q` so if you have already cloned that branch, do a git pull and rebuild to make sure it has the fix

**Comment by youyupei** [comment]
@Psy-Fer Thanks, I am just about to mention the bug.  I have it sorted, and it's running already. Thanks very much.

@hasindu2008 It's Tesla V100 as well. The `dna_r9.4.1_450bps_sup_Q7.cfg` is essentially the same as `dna_r9.4.1_450bps_sup` with a tiny modification of `min_qscore`.

**Comment by Psy-Fer** [comment]
Oh nice.

Getting better usage now?

**Comment by youyupei** [comment]
Yes, it looks much better.  I am quite happy with current speed already. But I guess it might be better to still let you know that it seems only one of the GPU is actually being used (I am using the command suggested by James above). Or I might have misunderstood the information showing in the picture below.

![image](https://user-images.githubusercontent.com/38273260/205036301-feda4f55-0616-4725-add2-79f22e2dfbd5.png)


Thanks very much again!!!!

**Comment by hasindu2008** [comment]
Can you please do a 
`watch -n0 nvidia-smi` and observe for a while to see if GPU 0 is always 0% or intermittent?

**Comment by youyupei** [comment]
Hi @hasindu2008, GPU 0 is not always. it seems the process is kinda switching between GPU 0 and 1. What I observed is: GPU 0 goes from 0% to ~100% and back to 0% then the same thing happens to GPU1.

**Comment by hasindu2008** [comment]
@youyupei 
the single BLOW5 is totally fine by the way -  that is how buttery-eel is meant to run. Could you please run the following command for a while and send the output?
```
nvidia-smi --format=csv --query-gpu=index,utilization.gpu -l 1
index, utilization.gpu [%]
0, 98 %
1, 88 %
2, 96 %
3, 97 %
0, 93 %
1, 98 %
2, 99 %
3, 94 %
0, 97 %
1, 99 %
2, 97 %
3, 91 %
0, 97 %
1, 97 %
2, 97 %
3, 95 %
0, 86 %
1, 94 %
2, 95 %
3, 94 %
0, 89 %
1, 95 %
2, 95 %
3, 97 %
0, 90 %
1, 100 %
2, 94 %
3, 95 %
0, 91 %
1, 93 %
2, 94 %
3, 95 %
0, 92 %
1, 96 %
2, 97 %
3, 97 %
0, 92 %
1, 94 %
2, 87 %
3, 96 %
0, 92 %
1, 97 %
2, 97 %
3, 99 %
0, 90 %
1, 93 %
2, 99 %
3, 96 %
0, 90 %
1, 96 %
2, 95 %
3, 97 %
```

As you can see, on our server when running sup on 4 GPUs, the utilisation is mostly <90%.
