### ISSUE TITLE
ValueError: Basecalling config unavailable: <result.basecall_config_unavailable: 6>

### ISSUE THREAD

**Issue by Grant-Fox** [Psy-Fer/buttery-eel#62]
Hello,

I ran this CLI: `BUTTERY-eel -g ../ont-dorado-server/bin/ --config ~/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac.cfg -i ../test/BLOW5/PAU73218_f2d0d057_ad2e3979_0.99_0.blow5 -o ../test/butterell_test.sam --port auto -x "cpu" --moves_out`

My output was: `~  buttery-eel - SLOW5 Guppy/Dorado Server Basecalling  ~
                            version: 0.6.0
==========================================================================
  ARGS
==========================================================================
args:
 Namespace(input='../test/BLOW5/PAU73218_f2d0d057_ad2e3979_0.99_0.blow5', output='../test/butterell_test.sam', basecaller_bin=PosixPath('../ont-dorado-server/bin'), config='/Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac.cfg', call_mods=False, qscore=None, slow5_threads=4, procs=4, slow5_batchsize=4000, quiet=False, max_read_queue_size=20000, log='buttery_basecaller_logs', moves_out=True, trim_adapters=False, seq_sum=False, barcode_kits=None, enable_trim_barcodes=False, require_barcodes_both_ends=False, U2T=False, duplex=False, single=False, profile=False, do_read_splitting=True, detect_adapter=False, detect_mid_strand_adapter=False, detect_mid_strand_barcodes=False, above_7310=True, above_7412=True)
['--port', 'auto', '-x', 'cpu']

==========================================================================
  Starting Guppy/Dorado Basecalling Server
==========================================================================
Address: ipc:///var/folders/xf/sng6mb3n6wg0l94p8jj6mx_w0000gr/T/6553-74f2-c1e8-25a3
Config: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac.cfg
Setting params...
Connecting...
[ont/error] basecall_client::Client::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac
[ont/error] basecall_client::Client::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac
[ont/error] basecall_client::Client::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac
[ont/error] basecall_client::Client::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac
[ont/error] basecall_client::Client::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac
[ont/error] basecall_client::Client::worker_loop: Connection error. [basecall_config_unavailable] could not retrieve details for config from server: /Users/grantfox/Downloads/ont-dorado-server/data/rna_rp4_130bps_hac
Traceback (most recent call last):
  File "/Users/grantfox/Downloads/buttery-eel/venv3/bin/BUTTERY-eel", line 33, in <module>
    sys.exit(load_entry_point('buttery-eel==0.6.0', 'console_scripts', 'buttery-eel')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grantfox/Downloads/buttery-eel/venv3/lib/python3.12/site-packages/buttery_eel-0.6.0-py3.12.egg/src/buttery_eel.py", line 138, in main
  File "/Users/grantfox/.pyenv/versions/3.12.0/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/grantfox/Downloads/buttery-eel/venv3/lib/python3.12/site-packages/buttery_eel-0.6.0-py3.12.egg/src/basecaller.py", line 136, in start_guppy_server_and_client
  File "/Users/grantfox/Downloads/buttery-eel/venv3/lib/python3.12/site-packages/ont_pybasecall_client_lib-7.4.12-py3.12-macosx-15.1-arm64.egg/pybasecall_client_lib/pyclient.py", line 378, in __enter__
    self.connect()
  File "/Users/grantfox/Downloads/buttery-eel/venv3/lib/python3.12/site-packages/ont_pybasecall_client_lib-7.4.12-py3.12-macosx-15.1-arm64.egg/pybasecall_client_lib/pyclient.py", line 172, in connect
    raise exception_type(exception_message)
ValueError: Basecalling config unavailable: <result.basecall_config_unavailable: 6>`

I am curious about getting assistance resolving the issue.

Thank you in advance! 

Grant

**Comment by Psy-Fer** [comment]
Hello Grant,

The basecalling config file should be just the name itself, and be located in the ../data folder from the bin folder you provide for dorado-sever 

So in this case, try running it with just `--config rna_rp4_130bps_hac.cfg` as the argument rather than as a path.

Also be aware that I've never tested buttery-eel with CPU mode. If it works, it will take a looooong time.

Let me know how you go,
Cheers,
James

**Comment by Psy-Fer** [comment]
Oh, you should probably also add `--use_tcp` as an argument. It's a Dorado server Arg that is passed through when controlling it 

(I should probably make this default, it's a legacy thing)

**Comment by Grant-Fox** [comment]
This fixed my issue thank you! @Psy-Fer and yes it is taking a loooong time....

**Comment by Psy-Fer** [comment]
Ahh great.

Yea basecalling is very much designed for GPUs.

Good luck. Let me know if any other issues arise.
James
